import Link from 'next/link'
import { SignIn, SignOut } from './components/AuthButtons'
import './globals.css'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import Form from './components/Form/Form'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <div>
          <Link href='/'>HOME</Link>
          <br/><br/>
          <Link href='/anotherPage'>ANOTHER PAGE</Link>
          <br/><br/>
        </div>
        <div>
          <h1>SESSION:</h1>
          <pre>{JSON.stringify(session)}</pre>
        </div>
        <SignIn />
        <SignOut />
        {children}
        <br/><br/>
        <div>
          <h1>Create a user</h1>
          <i>Side note: once created, will automatically sign in</i>
          <Form method='POST'/>
        </div>
      </body>
    </html>
  )
}
